vim.pack.add({ "https://github.com/sainnhe/gruvbox-material" })
vim.cmd([[colorscheme gruvbox-material]])

vim.cmd(":hi Normal guibg=none ctermbg=none")
vim.api.nvim_set_hl(0, "NormalNC", { bg = "none" })
vim.api.nvim_set_hl(0, "VertSplit", { bg = "none" })
vim.api.nvim_set_hl(0, "SignColumn", { bg = "none" })
vim.api.nvim_set_hl(0, "WinBar", { bg = "none" })
vim.api.nvim_set_hl(0, "WinBarNC", { bg = "none" })
vim.api.nvim_set_hl(0, "WinSeparator", { bg = "none", fg = "#3c3836" })
vim.api.nvim_set_hl(0, "StatusLine", { bg = "none" })
vim.api.nvim_set_hl(0, "StatusLineNC", { bg = "none" })
vim.api.nvim_set_hl(0, "TelescopeNormal", { link = "Folded" })
vim.api.nvim_set_hl(0, "TelescopeBorder", { link = "Folded" })
vim.api.nvim_set_hl(0, "TelescopePreviewBorder", { link = "Folded" })
vim.api.nvim_set_hl(0, "TelescopePromptTitle", { link = "TSNote" })
vim.api.nvim_set_hl(0, "TelescopePromptBorder", { link = "Visual" })
vim.api.nvim_set_hl(0, "TelescopePromptNormal", { link = "Visual" })
vim.api.nvim_set_hl(0, "TelescopePreviewTitle", { link = "TSDanger" })
vim.api.nvim_set_hl(0, "TelescopeSelection", { link = "Visual" })
vim.api.nvim_set_hl(0, "TelescopePromptCounter", { link = "Fg" })
vim.api.nvim_set_hl(0, "NoiceCmdlineIcon", { fg = "#7daea3", bold = true })
vim.api.nvim_set_hl(0, "NoiceCmdlinePopup", { link = "NormalFloat" })
vim.api.nvim_set_hl(0, "NoiceCmdlinePopupBorder", { fg = "#45403d", bg = "#45403d" })
vim.api.nvim_set_hl(0, "NoiceCmdlinePopupBorder", { fg = "#45403d", bg = "#45403d" })
vim.api.nvim_set_hl(0, "NoiceCmdlinePopupTitleInput", { link = "Blue" })
vim.api.nvim_set_hl(0, "SnacksInputNormal", { link = "NormalFloat" })
vim.api.nvim_set_hl(0, "SnacksInputBorder", { link = "NormalFloat" })
